import streamlit as st

# Define the questions and answers for each module and mock test
questions = {
    "Module 1: PET Design": {
        "Mock Test 1": [
            {"question": "What is the primary goal of PET design?", "options": ["Aesthetic appeal", "User satisfaction", "Persuasion", "Speed optimization"], "answer": "Persuasion"},
            {"question": "Which of the following is a key element of trust in PET design?", "options": ["Visual design", "User testimonials", "Animation", "Color schemes"], "answer": "User testimonials"},
            {"question": "What does the 'P' in PET design stand for?", "options": ["Performance", "Persuasion", "Psychology", "Perception"], "answer": "Persuasion"},
            {"question": "Which psychological principle is often used in PET design to influence user behavior?", "options": ["Reciprocity", "Aesthetics", "Navigation", "Speed"], "answer": "Reciprocity"},
            {"question": "Emotions in PET design are primarily aimed at:", "options": ["Distracting users", "Engaging users", "Confusing users", "Informing users"], "answer": "Engaging users"},
            {"question": "Trust in PET design can be increased by:", "options": ["Using flashy animations", "Displaying security badges", "Hiding terms and conditions", "Using complex language"], "answer": "Displaying security badges"},
            {"question": "The 'E' in PET design refers to:", "options": ["Efficiency", "Engagement", "Emotion", "Ease of use"], "answer": "Emotion"},
            {"question": "Persuasion in PET design is closely linked with:", "options": ["User interface design", "Cognitive biases", "Backend performance", "Loading speed"], "answer": "Cognitive biases"},
            {"question": "An example of using emotion in PET design is:", "options": ["Simplifying navigation", "Using warm colors", "Speeding up load times", "Providing detailed technical specifications"], "answer": "Using warm colors"},
            {"question": "Which principle is essential for creating persuasive designs?", "options": ["User boredom", "User delight", "Complexity", "Monotony"], "answer": "User delight"},
            {"question": "The principle of scarcity in PET design aims to:", "options": ["Increase user trust", "Encourage immediate action", "Reduce user engagement", "Lower user anxiety"], "answer": "Encourage immediate action"},
            {"question": "How does social proof work in PET design?", "options": ["By showing what other users are doing", "By hiding user activity", "By focusing on technical details", "By displaying random content"], "answer": "By showing what other users are doing"},
            {"question": "What is a common method to build trust in PET design?", "options": ["Using low-quality images", "Providing clear privacy policies", "Hiding terms of service", "Using complex jargon"], "answer": "Providing clear privacy policies"},
            {"question": "Which color is often associated with trust in design?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Blue"},
            {"question": "In PET design, emotions can be evoked using:", "options": ["Boring content", "High-quality visuals", "Confusing navigation", "Long loading times"], "answer": "High-quality visuals"},
            {"question": "The principle of authority in PET design involves:", "options": ["Displaying user testimonials", "Showing endorsements by experts", "Ignoring user feedback", "Providing minimal information"], "answer": "Showing endorsements by experts"},
            {"question": "Trust signals in PET design include:", "options": ["Security badges and certifications", "Flashy animations", "Complex navigation", "Bright colors"], "answer": "Security badges and certifications"},
            {"question": "How can the principle of reciprocity be used in PET design?", "options": ["By providing free resources", "By limiting user access", "By hiding information", "By using dark patterns"], "answer": "By providing free resources"},
            {"question": "What is a key factor in maintaining user trust?", "options": ["Consistent and reliable performance", "Frequent redesigns", "Complex user interfaces", "High user anxiety"], "answer": "Consistent and reliable performance"},
            {"question": "In PET design, emotions can be conveyed through:", "options": ["Boring layouts", "Engaging and interactive content", "Confusing navigation", "Monotonous color schemes"], "answer": "Engaging and interactive content"},
            {"question": "Persuasion in PET design can be achieved by:", "options": ["Providing clear and concise calls to action", "Using confusing language", "Ignoring user feedback", "Hiding information"], "answer": "Providing clear and concise calls to action"},
            {"question": "What does the 'T' in PET design stand for?", "options": ["Trust", "Timing", "Technology", "Trend"], "answer": "Trust"},
            {"question": "How can social proof be effectively implemented?", "options": ["By displaying user reviews and ratings", "By hiding user feedback", "By using complex language", "By ignoring user testimonials"], "answer": "By displaying user reviews and ratings"},
            {"question": "Which element is crucial for building user trust?", "options": ["Clear communication and transparency", "Confusing navigation", "Long loading times", "Complex user interfaces"], "answer": "Clear communication and transparency"},
            {"question": "Emotions in PET design can be triggered by:", "options": ["High-quality visuals and storytelling", "Boring content", "Confusing layouts", "Long load times"], "answer": "High-quality visuals and storytelling"},
            {"question": "The principle of scarcity aims to:", "options": ["Encourage immediate user action", "Reduce user engagement", "Lower user interest", "Increase user anxiety"], "answer": "Encourage immediate user action"},
            {"question": "Trust signals in PET design include:", "options": ["Clear and concise privacy policies", "Flashy animations", "Bright colors", "Complex navigation"], "answer": "Clear and concise privacy policies"},
            {"question": "How can the principle of authority be demonstrated?", "options": ["By showing endorsements by experts", "By hiding user feedback", "By using complex jargon", "By limiting information"], "answer": "By showing endorsements by experts"},
            {"question": "Persuasion in PET design can be enhanced by:", "options": ["Highlighting user benefits and features", "Using confusing language", "Ignoring user feedback", "Hiding information"], "answer": "Highlighting user benefits and features"},
            {"question": "Emotions in PET design can be conveyed through:", "options": ["Engaging and interactive content", "Boring layouts", "Confusing navigation", "Monotonous color schemes"], "answer": "Engaging and interactive content"},
            {"question": "How can social proof influence user decisions?", "options": ["By showing what other users are doing", "By hiding user activity", "By focusing on technical details", "By displaying random content"], "answer": "By showing what other users are doing"},
            {"question": "Which element is critical for building user trust?", "options": ["Clear communication and transparency", "Confusing navigation", "Long loading times", "Complex user interfaces"], "answer": "Clear communication and transparency"},
            {"question": "The principle of reciprocity can be implemented by:", "options": ["Providing free resources", "Limiting user access", "Hiding information", "Using dark patterns"], "answer": "Providing free resources"},
            {"question": "In PET design, emotions can be triggered by:", "options": ["High-quality visuals and storytelling", "Boring content", "Confusing layouts", "Long load times"], "answer": "High-quality visuals and storytelling"},
            {"question": "Trust signals in PET design include:", "options": ["Clear and concise privacy policies", "Flashy animations", "Bright colors", "Complex navigation"], "answer": "Clear and concise privacy policies"},
            {"question": "Persuasion in PET design can be achieved by:", "options": ["Providing clear and concise calls to action", "Using confusing language", "Ignoring user feedback", "Hiding information"], "answer": "Providing clear and concise calls to action"},
            {"question": "Emotions in PET design can be conveyed through:", "options": ["Engaging and interactive content", "Boring layouts", "Confusing navigation", "Monotonous color schemes"], "answer": "Engaging and interactive content"},
            {"question": "The principle of scarcity in PET design aims to:", "options": ["Increase user trust", "Encourage immediate action", "Reduce user engagement", "Lower user anxiety"], "answer": "Encourage immediate action"},
            {"question": "What is a common method to build trust in PET design?", "options": ["Using low-quality images", "Providing clear privacy policies", "Hiding terms of service", "Using complex jargon"], "answer": "Providing clear privacy policies"},
            {"question": "Which color is often associated with trust in design?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Blue"}
           
        ],
        "Mock Test 2": [
            {"question": "Which psychological principle is often used in PET design to influence user behavior?", "options": ["Reciprocity", "Aesthetics", "Navigation", "Speed"], "answer": "Reciprocity"},
            {"question": "Emotions in PET design are primarily aimed at:", "options": ["Distracting users", "Engaging users", "Confusing users", "Informing users"], "answer": "Engaging users"},
            {"question": "Trust in PET design can be increased by:", "options": ["Using flashy animations", "Displaying security badges", "Hiding terms and conditions", "Using complex language"], "answer": "Displaying security badges"},
            {"question": "The 'E' in PET design refers to:", "options": ["Efficiency", "Engagement", "Emotion", "Ease of use"], "answer": "Emotion"},
            {"question": "Persuasion in PET design is closely linked with:", "options": ["User interface design", "Cognitive biases", "Backend performance", "Loading speed"], "answer": "Cognitive biases"},
            {"question": "Which principle is essential for creating persuasive designs?", "options": ["User boredom", "User delight", "Complexity", "Monotony"], "answer": "User delight"},
            {"question": "The principle of scarcity in PET design aims to:", "options": ["Increase user trust", "Encourage immediate action", "Reduce user engagement", "Lower user anxiety"], "answer": "Encourage immediate action"},
            {"question": "How does social proof work in PET design?", "options": ["By showing what other users are doing", "By hiding user activity", "By focusing on technical details", "By displaying random content"], "answer": "By showing what other users are doing"},
            {"question": "What is a common method to build trust in PET design?", "options": ["Using low-quality images", "Providing clear privacy policies", "Hiding terms of service", "Using complex jargon"], "answer": "Providing clear privacy policies"},
            {"question": "Which color is often associated with trust in design?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Blue"},
            {"question": "An example of using emotion in PET design is:", "options": ["Simplifying navigation", "Using warm colors", "Speeding up load times", "Providing detailed technical specifications"], "answer": "Using warm colors"},
            {"question": "Which principle is critical for building user trust?", "options": ["Clear communication and transparency", "Confusing navigation", "Long loading times", "Complex user interfaces"], "answer": "Clear communication and transparency"},
            {"question": "The principle of reciprocity can be implemented by:", "options": ["Providing free resources", "Limiting user access", "Hiding information", "Using dark patterns"], "answer": "Providing free resources"},
            {"question": "In PET design, emotions can be triggered by:", "options": ["High-quality visuals and storytelling", "Boring content", "Confusing layouts", "Long load times"], "answer": "High-quality visuals and storytelling"},
            {"question": "Trust signals in PET design include:", "options": ["Clear and concise privacy policies", "Flashy animations", "Bright colors", "Complex navigation"], "answer": "Clear and concise privacy policies"},
            {"question": "Persuasion in PET design can be achieved by:", "options": ["Providing clear and concise calls to action", "Using confusing language", "Ignoring user feedback", "Hiding information"], "answer": "Providing clear and concise calls to action"},
            {"question": "Emotions in PET design can be conveyed through:", "options": ["Engaging and interactive content", "Boring layouts", "Confusing navigation", "Monotonous color schemes"], "answer": "Engaging and interactive content"},
            {"question": "The principle of scarcity in PET design aims to:", "options": ["Increase user trust", "Encourage immediate action", "Reduce user engagement", "Lower user anxiety"], "answer": "Encourage immediate action"},
            {"question": "What is a common method to build trust in PET design?", "options": ["Using low-quality images", "Providing clear privacy policies", "Hiding terms of service", "Using complex jargon"], "answer": "Providing clear privacy policies"},
            {"question": "Which color is often associated with trust in design?", "options": ["Red", "Blue", "Green", "Yellow"], "answer": "Blue"},
            {"question": "What is the primary goal of PET design?", "options": ["Aesthetic appeal", "User satisfaction", "Persuasion", "Speed optimization"], "answer": "Persuasion"},
            {"question": "Which of the following is a key element of trust in PET design?", "options": ["Visual design", "User testimonials", "Animation", "Color schemes"], "answer": "User testimonials"},
            {"question": "What does the 'P' in PET design stand for?", "options": ["Performance", "Persuasion", "Psychology", "Perception"], "answer": "Persuasion"}
            ],

        
        "Mock Test 3": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
    },

    "Module 2: Supporting Institutionalization of a Mature UX Practice": {
        "Mock Test 1": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            
            # Add more questions here...
        ],
        "Mock Test 2": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
        "Mock Test 3": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
    },

    "Module 3: Omni-Channel UX Strategy and Innovation": {
        "Mock Test 1": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            
            # Add more questions here...
        ],
        "Mock Test 2": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
        "Mock Test 3": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
    },

    "Module 4: The PET Architect": {
        "Mock Test 1": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            
            # Add more questions here...
        ],
        "Mock Test 2": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
        "Mock Test 3": [
            {"question": "Question 1?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 2?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 3?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 4?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 5?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 6?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 7?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 8?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 9?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 10?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 11?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 12?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 13?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 14?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 15?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 16?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 17?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 18?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 19?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 20?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 21?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 22?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 23?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 24?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 25?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 26?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 27?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 28?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 29?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 30?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 31?", "options": ["A", "B", "C", "D"], "answer": "A"},
            {"question": "Question 32?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 33?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 34?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 35?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 36?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 37?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 38?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 39?", "options": ["A", "B", "C", "D"], "answer": "B"},
            {"question": "Question 40?", "options": ["A", "B", "C", "D"], "answer": "B"}
            # Add more questions here...
        ],
    },
    # Define other modules and their mock tests similarly...
}

# App title
st.title("CXA Exam Preparation")

# Select module
module = st.selectbox("Select Module", list(questions.keys()))

if module:
    # Select mock test
    mock_test = st.selectbox("Select Mock Test", list(questions[module].keys()))

    if mock_test:
        # Get selected questions
        selected_questions = questions[module][mock_test]

        # User's answers
        user_answers = []

        for i, q in enumerate(selected_questions):
            st.write(f"Q{i+1}: {q['question']}")
            options = q['options']
            user_answer = st.radio(f"Select your answer for Q{i+1}", options, key=f"q{i+1}")
            user_answers.append({"question": q['question'], "user_answer": user_answer, "correct_answer": q['answer']})

        # Submit button
        if st.button("Submit"):
            score = sum(1 for a in user_answers if a['user_answer'] == a['correct_answer'])
            st.write(f"Your score is: {score}/{len(selected_questions)}")

            # Detailed feedback
            for i, a in enumerate(user_answers):
                st.write(f"Q{i+1}: {a['question']}")
                st.write(f"Your answer: {a['user_answer']} | Correct answer: {a['correct_answer']}")
